"""
Persona system: create LlamAgents with different identities, each persona having independent memory and tools.

Creation workflow (target architecture):
    The user only needs to provide a name + a one-line role description (e.g., "frontend development expert"),
    and the system calls LLM to automatically expand it into a complete system prompt.

Usage:
    manager = PersonaManager("/path/to/personas.json")
    coder = manager.create("Code Llama", role_description="frontend development expert")
    agent = LlamAgent(config, persona=coder)
"""

import hashlib
import json
import logging
import os
import re
from dataclasses import dataclass, asdict, field
from datetime import datetime

logger = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    """
    Convert a name to an ASCII-safe ID (for ChromaDB collection names, filenames, etc.).

    English + digits are joined with underscores; pure non-ASCII names (e.g., Chinese) use an MD5 short hash.
    """
    # Keep English letters and digits, replace everything else with underscores
    ascii_part = re.sub(r"[^a-zA-Z0-9]+", "_", text.lower()).strip("_")
    if ascii_part:
        return ascii_part
    # Pure non-ASCII names, use a short hash
    short_hash = hashlib.md5(text.encode()).hexdigest()[:8]
    return f"persona_{short_hash}"


@dataclass
class Persona:
    """
    LlamAgent persona definition.

    Field descriptions:
    - name: Display name (e.g., "Code Llama")
    - role_description: User-provided role description (e.g., "frontend development expert"), used for LLM auto-expansion
    - system_prompt: Complete persona prompt (auto-generated by LLM expansion, or manually specified)
    - role: Permission role "admin" (administrator) or "user" (regular user)
    - permission_level: Permission level (admin defaults to 3, user defaults to 1, can be manually adjusted)
    - persona_id: Unique ID (auto-generated from name; non-ASCII names use MD5 short hash)
    - created_at: Creation time (ISO format, auto-generated)
    """

    name: str                              # Display name
    role_description: str = ""             # User-provided role description
    system_prompt: str = ""                # Complete persona prompt (LLM-expanded or manually specified)
    role: str = "user"                     # Permission role: "admin" | "user"
    permission_level: int | None = None     # Permission level (None means auto, set by role)
    persona_id: str = ""                   # Unique ID
    created_at: str = ""                   # Creation time

    def __post_init__(self):
        # Auto-generate persona_id
        if not self.persona_id:
            self.persona_id = _slugify(self.name)

        # Auto-generate creation time
        if not self.created_at:
            self.created_at = datetime.now().isoformat()

        # Auto-set permission level: admin defaults to 3, user defaults to 1
        if self.permission_level is None:
            self.permission_level = 3 if self.role == "admin" else 1

        # Role validity check
        if self.role not in ("admin", "user"):
            logger.warning("role='%s' is invalid, falling back to 'user'", self.role)
            self.role = "user"

    @property
    def is_admin(self) -> bool:
        """Whether this is an administrator persona."""
        return self.role == "admin"

    def to_system_prompt(self) -> str:
        """
        Convert persona information to a system prompt.

        Prefers the LLM-generated system_prompt field;
        falls back to constructing from role_description if empty.
        """
        # If a complete system_prompt exists, use it directly
        if self.system_prompt:
            base = self.system_prompt
        elif self.role_description:
            # Fallback: simple construction from role_description
            base = f"Your name is {self.name}. {self.role_description}"
        else:
            base = f"Your name is {self.name}."

        parts = [base]

        # Administrator permission description
        if self.is_admin:
            parts.append(
                "\n[Administrator Privileges]\n"
                "You are an administrator with elevated privileges:\n"
                "- You can create 'common tools' that all llamas can use\n"
                "- You can view custom tools created by all llamas\n"
                "- You can promote excellent custom tools to common tools\n"
                "- You are responsible for maintaining toolbox quality; carefully review tool code for safety"
            )

        return "\n".join(parts)


class PersonaManager:
    """
    Persona manager: create, list, load, and delete personas.

    All personas are persisted to a single JSON file with a simple structure for easy manual editing.
    During creation, you can optionally call LLM to auto-expand the role description into a complete system prompt.
    """

    def __init__(self, storage_path: str, llm=None):
        """
        Initialize the persona manager.

        Args:
            storage_path: Persona definition JSON file path
            llm: Default LLMClient instance (optional), used when create() is called without an llm argument
        """
        self.storage_path = storage_path
        self.llm = llm
        self._personas: dict[str, Persona] = {}
        self._load()

    def create(
        self,
        name: str,
        role_description: str,
        role: str = "user",
        permission_level: int | None = None,
        persona_id: str = "",
        llm=None,
    ) -> Persona:
        """
        Create and save a new persona.

        If an llm (LLMClient instance) is provided, the model is called to auto-expand
        role_description into a complete system_prompt. Otherwise system_prompt is left empty,
        and to_system_prompt() falls back to constructing from role_description at runtime.

        Args:
            name: Display name
            role_description: Role description (e.g., "frontend development expert")
            role: Permission role "admin" | "user"
            permission_level: Permission level; None auto-sets by role (admin=3, user=1)
            persona_id: Unique ID; empty string auto-generates from name
            llm: LLMClient instance (optional), used to auto-expand system_prompt

        Returns:
            The created Persona object

        Raises:
            ValueError: Raised when persona_id already exists
        """
        # Determine permission level
        if permission_level is None:
            actual_level = None  # Let __post_init__ handle automatically
        else:
            actual_level = permission_level

        # Auto-expand system_prompt
        effective_llm = llm if llm is not None else self.llm
        system_prompt = ""
        if effective_llm is not None:
            system_prompt = self._expand_system_prompt(effective_llm, name, role_description, role)

        persona = Persona(
            name=name,
            role_description=role_description,
            system_prompt=system_prompt,
            role=role,
            permission_level=actual_level,
            persona_id=persona_id,
        )

        if persona.persona_id in self._personas:
            raise ValueError(f"Persona ID '{persona.persona_id}' already exists")

        self._personas[persona.persona_id] = persona
        self._save()
        logger.info("Persona created: %s (ID: %s, role: %s)", name, persona.persona_id, role)
        return persona

    def get(self, persona_id: str) -> Persona | None:
        """Get a persona by ID. Returns None if not found."""
        return self._personas.get(persona_id)

    def list(self) -> list[Persona]:
        """List all created personas."""
        return list(self._personas.values())

    def delete(self, persona_id: str) -> bool:
        """
        Delete a persona. Returns True on success, False if not found.

        Note: This does not clear memory data associated with the persona; manual cleanup is required.
        """
        if persona_id in self._personas:
            name = self._personas[persona_id].name
            del self._personas[persona_id]
            self._save()
            logger.info("Persona deleted: %s (ID: %s)", name, persona_id)
            return True
        return False

    # ------------------------------------------------------------------
    # Internal methods
    # ------------------------------------------------------------------

    def _expand_system_prompt(
        self, llm, name: str, role_description: str, role: str
    ) -> str:
        """
        Call LLM to expand a role description into a complete system prompt.

        Returns an empty string on failure; Persona.to_system_prompt() handles the fallback.
        """
        expand_prompt = (
            f"Please generate a complete system prompt for an AI assistant persona.\n\n"
            f"Persona name: {name}\n"
            f"Role description: {role_description}\n"
            f"Permission role: {'administrator' if role == 'admin' else 'regular user'}\n\n"
            f"Requirements:\n"
            f"1. Use second person ('You are...')\n"
            f"2. Include identity positioning, areas of expertise, behavioral style, and response approach\n"
            f"3. Keep it concise (200-400 words)\n"
            f"4. Output only the system prompt content, no additional explanations"
        )
        try:
            result = llm.ask(expand_prompt, temperature=0.7)
            if result and not result.startswith("[LLM"):
                logger.info("Successfully generated system prompt for persona '%s'", name)
                return result.strip()
        except Exception as e:
            logger.warning("Auto-expanding system prompt failed: %s", e)
        return ""

    def _load(self):
        """Load persona data from the JSON file."""
        if not os.path.exists(self.storage_path):
            return
        try:
            with open(self.storage_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            for item in data:
                # Compatibility with legacy data structure (identity + purpose -> role_description + system_prompt)
                if "identity" in item and "role_description" not in item:
                    item["role_description"] = item.pop("identity", "")
                    purpose = item.pop("purpose", "")
                    if purpose:
                        item["role_description"] += f" {purpose}"
                    # Legacy format has no system_prompt field
                    item.setdefault("system_prompt", "")
                # Legacy format has no permission_level field
                item.setdefault("permission_level", None)
                # Remove fields that may exist in legacy format but are not needed in the new version
                known_fields = {
                    "name", "role_description", "system_prompt", "role",
                    "permission_level", "persona_id", "created_at",
                }
                item = {k: v for k, v in item.items() if k in known_fields}
                p = Persona(**item)
                self._personas[p.persona_id] = p
        except (json.JSONDecodeError, IOError, TypeError) as e:
            logger.warning("Failed to load persona file (%s): %s", self.storage_path, e)

    def _save(self):
        """Save persona data to the JSON file."""
        dir_path = os.path.dirname(self.storage_path)
        if dir_path:
            os.makedirs(dir_path, exist_ok=True)
        try:
            with open(self.storage_path, "w", encoding="utf-8") as f:
                json.dump(
                    [asdict(p) for p in self._personas.values()],
                    f,
                    ensure_ascii=False,
                    indent=2,
                )
        except IOError as e:
            logger.error("Failed to save persona file (%s): %s", self.storage_path, e)
